### ISSUE TITLE
All response typings should be wrapped on a 'data' key

### ISSUE THREAD

**Issue by redeven** [Api-Wrappers/anilist-wrapper#3]
All queries and mutations expect the currently typed response type to be returned, eg
```ts
this.anilist.user.updateMedia({ mediaId, progress }).then((response: SaveMediaListEntry) => {});
```
When that object is actually one level deeper, such as
```ts
this.anilist.user.updateMedia({ mediaId, progress }).then((response: { data: SaveMediaListEntry }) => {});
```
This forces me to manually cast it to fix the typings, so that it doesn't break:
```ts
this.anilist.user.updateMedia({ mediaId: entry.media.id, progress: entry.progress + 1 }) as any as Promise<{
    data: { SaveMediaListEntry: ShowMutations };
}>
```

Here's a screenshot of the current way all Anilist api responses are being sent:
![image](https://github.com/Api-Wrappers/anilist-wrapper/assets/18680184/5e7b305b-cf52-43a8-8af2-b93cab8d2b00)

**Comment by TDanks2000** [comment]
Feel free to create a pr :)
